version: "2.6.1"
services: 
  mysql:
    container_name: mysql
    platform: linux/x86_64
    image: mysql:5.7.25
    volumes:
      - ./sql-data/db:/var/lib/mysql
    ports:
      - "23306:3306"
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'supermarketdb'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'